pcall(require, "impatient")

require('user.settings')
require('user.plugins')
require('user.keymaps')
require('user.treesitter')
require('user.alpha')
require('user.nvim-tree')
require('user.lsp')
require('user.dap')
require('user.cmp')
require('user.ufo')
require('user.comment')
require('user.telescope')
require('user.lualine')
require('user.indent-blankline')
require('user.hop')
require('user.bufferline')
require('user.trouble')
require('user.toggleterm')
require('user.git')
require('user.colorizer')
require('user.undotree')
require('user.icons')
