vim.defer_fn(function()
  pcall(require, "impatient")
end, 0)

require('user.plugins')
require('user.settings')
require('user.keymaps')
require('user.theme')
require('user.lualine')
require('user.indent-blankline')
require('user.cmp')
require('user.lsp')
require('user.treesitter')
require('user.telescope')
require('user.dashboard')
require('user.hop')
require('user.comment')
require('user.dap')
require('user.bufferline')
require('user.trouble')
require('user.toggleterm')
require('user.whichkey')
