---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    is_ubuntu18: "{{ ansible_facts.distribution == 'Ubuntu' and
      ansible_facts.distribution_major_version == '18' }}"
    is_debian10: "{{ ansible_facts.distribution == 'Debian' and
      ansible_facts.distribution_major_version == '10' }}"

  pre_tasks:
    - name: Update (Debian)
      ansible.builtin.apt:
        name: python3-apt
        update_cache: true
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

  #   - name: Update (MacOS)
  #     community.general.homebrew:
  #       update_homebrew: true
  #       upgrade_all: true
  #       upgrade_options: ignore-pinned
  #     when: ansible_facts['os_family'] == "Darwin"

  roles:
    - nvim
    - tmux
    - zsh
    - git

  # tasks:
  #   - import_tasks: tasks/termapps.yml
