---
- hosts: all
  gather_facts: true
  become: true
  become_user: "{{ user_name }}"

  tasks:

    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/termapps.yml
    - import_tasks: tasks/zsh.yml

