---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  become_user: "{{ user_name }}"
  vars:
    is_ubuntu18: "{{ ansible_facts.distribution == 'Ubuntu' and
      ansible_facts.distribution_major_version == '18' }}"
    is_debian10: "{{ ansible_facts.distribution == 'Debian' and
      ansible_facts.distribution_major_version == '10' }}"

  pre_tasks:
    - name: Update (Debian)
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      become: true
      become_user: root
      when: ansible_facts['os_family'] == "Debian"

    - name: Update (MacOS)
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
        upgrade_options: ignore-pinned
      when: ansible_facts['os_family'] == "Darwin"

  roles:
    - nvim
    - tmux
    - zsh
    - git

  tasks:
    - import_tasks: tasks/termapps.yml
