- name: Install apps with brew
  homebrew_cask:
    name: 
      - signal
      - bitwarden
      - spotify
      - google-chrome
      - firefox
      - discord
      - visual-studio-code
      - steam
      - nextcloud
      - sublime-text
      - raspberry-pi-imager
      - arduino
      - minecraft
      - android-studio
      - whatsapp
      - godot
      - mullvadvpn
      - zoom
    state: latest
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Install apps as flatpak
  flatpak:
    name:
      - org.signal.Signal
      - com.bitwarden.desktop
      - com.spotify.Client
      - com.google.Chrome
      - org.mozilla.firefox 
      - com.discordapp.Discord
      - com.visualstudio.code
      - com.valvesoftware.Steam
      - com.nextcloud.desktopclient.nextcloud
      - com.sublimetext.three
      - org.raspberrypi.rpi-imager
      - cc.arduino.arduinoide
      - com.mojang.Minecraft
      - com.google.AndroidStudio
      - org.godotengine.Godot
      - us.zoom.Zoom
    state: present
    method: system
  when:
    ansible_facts['os_family'] == "Debian"


