- name: Install apps with brew
  homebrew_cask:
    name: 
      - signal
      - bitwarden
      - spotify
      - google-chrome
      - firefox
      - discord
      - visual-studio-code
      - steam
      - nextcloud
      - sublime-text
      - raspberry-pi-imager
      - arduino
      - minecraft
      - android-studio
      - whatsapp
      - godot
      - mullvadvpn
      - zoom
    state: latest
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Install apps as flatpak
  flatpak:
    name:
      - org.signal.Signal
    state: present
    method: system
    remote: flathub
  when:
    ansible_facts['os_family'] == "Debian"


