- name: Install flatpak, gnome software
  apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
  become: true
  become_user: root

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
