- name: Set git default branch
  git_config:
    name: init.defaultBranch
    scope: global
    value: master

- name: set default editor for git
  git_config:
    name: core.editor
    scope: global
    value: nvim
