- name: Install git with homebrew
  homebrew:
    name: git
    state: latest

- name: Set git user name
  git_config:
    name: user.name
    scope: global
    value: ""

- name: Set git user email
  git_config:
    name: user.email
    scope: global
    value: ""

- name: Set git default branch
  git_config:
    name: init.defaultBranch
    scope: global
    value: master

- name: set default editor for git
  git_config:
    name: core.editor
    scope: global
    value: "{{ 'nvim' if ansible_facts['os_family'] == 'Darwin' else 'neovim' }}"
