- name: Set nvim path
  set_fact:
    nvim_path: "~/.config/nvim"
  become: true
  become_user: "{{ user_name }}"

- name: Install required packages
  homebrew:
    name: "{{ item }}"
    state: latest
    with_items:
      - nvim
      - curl
      - git
      - node
  become: true
  become_user: "{{ user_name }}"

- name: Install lsp servers with homebrew
  homebrew:
    name: "{{ item }}"
    state: latest
    with_items:
      - pyright
      - gopls
      - llvm
      - lua-language-server
  become: true
  become_user: "{{ user_name }}"

- name: Install lsp servers with npm
  npm:
    name: "{{ item }}"
    global: true
    state: latest
    with_items:
      - ansible-language-server
  become: true
  become_user: "{{ user_name }}"

- name: Install lsp servers with pip
  pip:
    name: "{{ item }}"
    with_items:
      - cmake-language-server
  become: true
  become_user: "{{ user_name }}"

- name: Make sure ~/.config/nvim exists
  file:
    path: "{{ nvim_path }}"
    state: directory
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: Copy config files
  copy:
    src: files/nvim/
    dest: "{{ nvim_path }}"
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim
  become: true
  become_user: "{{ user_name }}"

#- name: Install Plugins
  #shell: nvim -c PlugInstall -c q -c q
