---
- name: Set nvim path
  set_fact:
    nvim_path: "~/.config/nvim"

- name: Install required packages with brew
  homebrew:
    name:
      - nvim
      - curl
      - git
      - gopls
      - llvm
      - lua-language-server
    state: latest
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Install required packages with apt
  apt:
    name:
      - curl
      - git
      - python3-pip
      - golang
      - llvm
    state: latest
    update_cache: true
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Install neovim from tarball, unzip tarball
  unarchive:
    src:
      "https://github.com/neovim/neovim/releases/download/\
      v0.7.0/nvim-linux64.tar.gz"
    dest: "/home/{{ user_name }}/"
    remote_src: true
  when: >
    ansible_facts['os_family'] == "Debian" and
    ansible_architecture == "x86_64"

- name: Install neovim from tarball, copy nvim to /usr/bin
  copy:
    src: "/home/{{ user_name }}/nvim-linux64/bin/nvim"
    dest: "/usr/bin/nvim"
    owner: root
    group: root
    mode: '0555'
    remote_src: true
  become: true
  become_user: root
  when: >
    ansible_facts['os_family'] == "Debian" and
    ansible_architecture == "x86_64"

- name: Install neovim from source, Install required packages
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
    state: latest
  become: true
  become_user: root
  when: >
    ansible_facts['os_family'] == "Debian" and
    ansible_architecture != "x86_64"

- name: Download neovim source
  git:
    repo: https://github.com/neovim/neovim
    dest: "/home/{{ user_name }}/neovim"
    clone: true
    update: false
    version: stable
  when: >
    ansible_facts['os_family'] == "Debian" and
    ansible_architecture != "x86_64"

- name: Build neovim
  make:
    chdir: "/home/{{ user_name }}/neovim"
    target: install
    params:
      NUM_THREADS: 4
      CMAKE_BUILD_TYPE: Release
      CMAKE_INSTALL_PREFIX: build
  when: >
    ansible_facts['os_family'] == "Debian" and
    ansible_architecture != "x86_64"

- name: Copy nvim bin to /usr/bin
  copy:
    src: "/home/{{ user_name }}/neovim/build/bin/nvim"
    dest: /usr/bin/
    owner: root
    group: root
    mode: '0555'
    remote_src: true
  become: true
  become_user: root
  when: >
    ansible_facts['os_family'] == "Debian" and
    ansible_architecture != "x86_64"

- name: Install lsp servers with pip
  pip:
    name:
      - cmake-language-server
      - pyright
    executable: pip3

- name: Make sure ~/.config/nvim and subdirectories exists
  file:
    path: "{{ nvim_path }}/{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group:
      "{{ 'staff' if ansible_facts['os_family'] == 'Darwin'
      else user_name }}"
    mode: 0750
  with_items:
    - "autoload"

- name: Copy config files
  copy:
    src: files/nvim/
    dest: "{{ nvim_path }}/"
    owner: "{{ user_name }}"
    group:
      "{{ 'staff' if ansible_facts['os_family'] == 'Darwin'
      else user_name }}"
    mode: 0750

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim
