- name: Set nvim path
  set_fact:
    nvim_path: "~/.config/nvim"

- name: Install required packages
  homebrew:
    name: 
      - nvim
      - curl
      - git
      - node
    state: latest

- name: Install lsp servers with homebrew
  homebrew:
    name:
      - pyright
      - gopls
      - llvm
      - lua-language-server
    state: latest

- name: Install lsp servers with pip
  pip:
    name:
      - cmake-language-server

- name: Make sure ~/.config/nvim exists
  file:
    path: "{{ nvim_path }}"
    state: directory
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: Make sure ~/.config/nvim exists
  file:
    path: "{{ nvim_path }}/{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: staff
    mode: 0750
  with_items:
    - "autoload"

- name: copy files
  copy:
    src: files/nvim/
    dest: "{{ nvim_path }}/"
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim

- name: Install Plugins
  shell: nvim -c PlugInstall -c q -c q
