- name: Set nvim path
  set_fact:
    nvim_path: "~/.config/nvim"

- name: Install required packages with brew
  homebrew:
    name: 
      - nvim
      - curl
      - git
      - gopls
      - llvm
      - lua-language-server
    state: latest
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Install neovim from source, Install required packages
  apt:
    name: 
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
    state: latest
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Download neovim source
  git:
    repo: https://github.com/neovim/neovim
    dest: "/home/{{ user_name }}/neovim"
    clone: yes
    version: stable
  when:
    ansible_facts['os_family'] == "Debian"

- name: Build neovim
  make:
    chdir: "/home/{{ user_name }}/neovim"
    target: install
    params:
      CMAKE_BUILD_TYPE: Release
      CMAKE_INSTALL_PREFIX: build
  when:
    ansible_facts['os_family'] == "Debian"

- name: Copy nvim bin to /usr/bin
  copy:
    src: "/home/{{ user_name }}/neovim/build/bin/nvim"
    dest: /usr/bin/
    owner: root
    group: root
    mode: '0555'
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Install required packages with apt
  apt:
    name: 
      - curl
      - git
      - python3-pip
      - golang
      - llvm
    state: latest
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Install gopls on Debian
  shell: export GO111MODULE=on && go get golang.org/x/tools/gopls@latest
  when:
    ansible_facts['os_family'] == "Debian"

- name: Install lsp servers with pip
  pip:
    name:
      - cmake-language-server
      - pyright

- name: Make sure ~/.config/nvim and subdirectories exists
  file:
    path: "{{ nvim_path }}/{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ 'staff' if ansible_facts['os_family'] == 'Darwin' else user_name }}"
    mode: 0750
  with_items:
    - "autoload"

- name: Copy config files
  copy:
    src: files/nvim/
    dest: "{{ nvim_path }}/"
    owner: "{{ user_name }}"
    group: "{{ 'staff' if ansible_facts['os_family'] == 'Darwin' else user_name }}"
    mode: 0750

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim

