- name: Set nvim path
  set_fact:
    nvim_path: "~/.config/nvim"
  become: true
  become_user: "{{ user_name }}"

- name: Install required packages
  homebrew:
    name: 
      - nvim
      - curl
      - git
      - node
    state: latest
  become: true
  become_user: "{{ user_name }}"

- name: Install lsp servers with homebrew
  homebrew:
    name:
      - pyright
      - gopls
      - llvm
      - lua-language-server
    state: latest
  become: true
  become_user: "{{ user_name }}"

- name: Install lsp servers with pip
  pip:
    name:
      - cmake-language-server
  become: true
  become_user: "{{ user_name }}"

- name: Make sure ~/.config/nvim exists
  file:
    path: "{{ nvim_path }}"
    state: directory
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: Make sure ~/.config/nvim exists
  file:
    path: "{{ nvim_path }}/{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: staff
    mode: 0750
  with_items:
    - "autoload"
    - "lua"
    - "ftplugin"

- name: copy files
  copy:
    src: files/nvim/init.vim
    dest: "{{ nvim_path }}/init.vim"
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: copy files
  copy:
    src: files/nvim/ftplugin/markdown.vim
    dest: "{{ nvim_path }}/ftplugin/markdown.vim"
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: copy files
  copy:
    src: files/nvim/ftplugin/yaml.vim
    dest: "{{ nvim_path }}/ftplugin/yaml.vim"
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: copy files
  copy:
    src: files/nvim/lua/lsp-config.lua
    dest: "{{ nvim_path }}/lua/lsp-config.lua"
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: copy files
  copy:
    src: files/nvim/lua/nvim-cmp.lua
    dest: "{{ nvim_path }}/lua/nvim-cmp.lua"
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: copy files
  copy:
    src: files/nvim/lua/treesitter/lua
    dest: "{{ nvim_path }}/lua/treesitter/lua"
    owner: "{{ user_name }}"
    group: staff
    mode: 0750

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim
  become: true
  become_user: "{{ user_name }}"

#- name: Install Plugins
  #shell: nvim -c PlugInstall -c q -c q
