- name: Setup your sources.list
  shell: echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list
  become: true
  become_user: root

- name: Set up your keys
  apt_key:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
    state: present
  become: true
  become_user: root

- name: Installation
  apt:
    update_cache: yes
    name:
      - ros-noetic-desktop-full
  become: true
  become_user: root

- name: Environment setup
  lineinfile:
    path: ~/.bashrc
    line: 'source /opt/ros/noetic/setup.bash'

- name: Dependencies for building packages
  apt:
    name:
      - python3-rosdep
      - python3-rosinstall
      - python3-rosinstall-generator
      - python3-wstool
      - build-essential
      - python3-rosdep
  become: true
  become_user: root

- name: Initializing rosdep
  shell: rosdep init
  become: true
  become_user: root
  ignore_errors: yes

- name: Update rosdep
  shell: rosdep update




