- name: Setup your sources.list
  shell: echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-melodic.list
  become: true
  become_user: root

- name: Set up your keys
  apt_key:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
    state: present
  become: true
  become_user: root

- name: Installation
  apt:
    update_cache: yes
    name:
      - ros-melodic-desktop-full
  become: true
  become_user: root

- name: Environment setup
  lineinfile:
    path: ~/.bashrc
    line: 'source /opt/ros/melodic/setup.bash'

- name: Dependencies for building packages
  apt:
    name:
      - python-rosdep
      - python-rosinstall
      - python-rosinstall-generator
      - python-wstool
      - build-essential
      - python-rosdep

- name: Initializing rosdep
  shell: rosdep init
  become: true
  become_user: root
  ignore_errors: yes

- name: Update rosdep
  shell: rosdep update


