- name: Add the ROS 2 apt repository, install required packages
  apt:
    name:
      - curl
      - gnupg2
      - lsb-release
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Add the ROS 2 apt repository, download gpg key and add repo to sources
  get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Add the ROS 2 apt repository, add repo to sources
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
  when:
    ansible_facts['os_family'] == "Debian"


#- name: Download ros2
  #get_url:
    #url: https://github.com/ros2/ros2/releases/download/release-foxy-20220208/ros2-foxy-20220208-linux-focal-amd64.tar.bz2
    #dest: ~/ros2-package-linux-x86_64.tar.bz2

- name: Create ros2 dir
  file:
    path: ~/ros2_foxy
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755

- name: unzip ros2 
  unarchive:
    src: ~/ros2-package-linux-x86_64.tar.bz2
    dest: ~/ros2_foxy/
