---
- name: Add the ROS 2 apt repository, install required packages
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - lsb-release
    update_cache: true
  become: true
  become_user: root

- name: >
    Add the ROS 2 apt repository,
    download gpg key and add repo to sources
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg
  become: true
  become_user: root

- name: Add the ROS 2 apt repository, add repo to sources
  ansible.builtin.shell: >
    echo "deb [arch=$(dpkg --print-architecture)
    signed-by=/usr/share/keyrings/ros-archive-keyring.gpg]
    http://packages.ros.org/ros2/ubuntu focal main" |
    sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

- name: update and upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true
  become_user: root

- name: install ros2
  ansible.builtin.apt:
    name:
      - ros-foxy-ros-base
    update_cache: true
  become: true
  become_user: root

- name: Install Gazebo
  ansible.builtin.apt:
    name:
      - ros-foxy-gazebo-ros-pkgs
  become: true
  become_user: root
