---
- name: Make sure /usr/loca/sbin exists
  ansible.builtin.file:
    path: /usr/local/sbin
    state: directory
    owner: "{{ user_name }}"
    group: admin
    mode: 0775
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Copy first names
  ansible.builtin.copy:
    src: files/spoof/first-names.txt
    dest: /usr/local/sbin/first-names.txt
    owner: "{{ user_name }}"
    group: admin
    mode: 0440
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Copy mac adresses
  ansible.builtin.copy:
    src: files/spoof/mac-address-prefixes.txt
    dest: /usr/local/sbin/mac-address-prefixes.txt
    owner: "{{ user_name }}"
    group: admin
    mode: 0440
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Copy spoof.sh
  ansible.builtin.copy:
    src: files/spoof/spoof.sh
    dest: /usr/local/sbin/spoof.sh
    owner: "{{ user_name }}"
    group: admin
    mode: 0550
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Copy spoof-hook.sh
  ansible.builtin.copy:
    src: files/spoof/spoof-hook.sh
    dest: /usr/local/sbin/spoof-hook.sh
    owner: "{{ user_name }}"
    group: admin
    mode: 0550
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Copy local.spoof.plist
  ansible.builtin.copy:
    src: files/spoof/local.spoof.plist
    dest: /Library/LaunchDaemons/local.spoof.plist
    owner: root
    group: wheel
    mode: 0440
  become: true
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Set logout hook
  ansible.builtin.shell: >
    defaults write com.apple.loginwindow
    LogoutHook "/usr/local/sbin/spoof-hook.sh"
  become: true
  when:
    ansible_facts['os_family'] == "Darwin"
