---
- name: Install apps with brew
  homebrew:
    name:
      - neofetch
      - htop
    state: present
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Install apps with apt
  apt:
    name:
      - neofetch
      - htop
      - net-tools
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"
