---
- name: Set is_ubuntu18_or_debian10 to true
  ansible.builtin.set_fact:
    is_ubuntu18_or_debian10: true
  when: >
    (ansible_facts['distribution'] == "Ubuntu" and
    ansible_facts['distribution_major_version'] == "18") or
    (ansible_facts['distribution'] == "Debian" and
    ansible_facts['distribution_major_version'] == "10")

- name: Set is_ubuntu18_or_debian10 to false
  ansible.builtin.set_fact:
    is_ubuntu18_or_debian10: false
  when: >
    not ((ansible_facts['distribution'] == "Ubuntu" and
    ansible_facts['distribution_major_version'] == "18") or
    (ansible_facts['distribution'] == "Debian" and
    ansible_facts['distribution_major_version'] == "10"))

- name: Install required packages with brew
  homebrew:
    name:
      - tmux
    state: present
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Install tmux with apt
  ansible.builtin.apt:
    name:
      - tmux
    state: present
    update_cache: true
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian" and
    not is_ubuntu18_or_debian10

- name: Make sure tmux-source folder exists
  ansible.builtin.file:
    path: ~/tmux-source
    state: directory
    mode: '0766'
  when: is_ubuntu18_or_debian10

- name: Download tmux source code
  ansible.builtin.unarchive:
    src: https://github.com/tmux/tmux/releases/download/3.3a/tmux-3.3a.tar.gz
    dest: ~/tmux-source
    mode: '0660'
    remote_src: true
    extra_opts: [--strip-components=1]
  when: is_ubuntu18_or_debian10

- name: Install build dependencies
  ansible.builtin.apt:
    name:
      - libevent-dev
      - ncurses-dev
      - build-essential
      - bison
      - pkg-config
  become: true
  become_user: root
  when: is_ubuntu18_or_debian10

- name: Run configure
  ansible.builtin.shell: cd ~/tmux-source && sh ./configure
  when: is_ubuntu18_or_debian10

- name: Compile tmux
  community.general.make:
    chdir: ~/tmux-source
  when: is_ubuntu18_or_debian10

- name: Run install
  community.general.make:
    chdir: '/home/{{ user_name }}/tmux-source'
    target: install
  become: true
  become_user: root
  when: is_ubuntu18_or_debian10

- name: Copy tmux config file
  ansible.builtin.copy:
    src: files/tmux/.tmux.conf
    dest: ~/.tmux.conf
    mode: 0640

- name: Check if tpm is installed
  ansible.builtin.stat:
    path: ~/.tmux/plugins/tpm
  register: tpm_installed

- name: Install tmux tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    version: master
  when: not tpm_installed.stat.exists
