---
- name: Install required packages with brew
  homebrew:
    name:
      - tmux
    state: present
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Install required packages with apt
  ansible.builtin.apt:
    name:
      - tmux
    state: present
    update_cache: true
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Copy config file
  ansible.builtin.copy:
    src: files/tmux/.tmux.conf
    dest: ~/.tmux.conf
    mode: 0640

- name: Install tmux tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  ignore_errors: true
