- name: Install required packages with brew
  homebrew:
    name: 
      - tmux
    state: present
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Install required packages with apt
  apt:
    name: 
      - tmux
    state: present
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Make sure ~/.tmux folder exists
  file:
    path: "~/.tmux"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ 'staff' if ansible_facts['os_family'] == 'Darwin' else user_name }}"
    mode: 0750

- name: Copy config file
  copy:
    src: files/tmux/.tmux.conf
    dest: ~/.tmux.conf
    mode: 0640

- name: Copy config file
  copy:
    src: files/tmux/.tmux.conf.local
    dest: ~/.tmux/.tmux.conf.local
    mode: 0640


- name: Install tmux tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
