- name: Update deb packages
  apt:
    update_cache: yes
    upgrade: yes
  when:
    ansible_facts['os_family'] == "Debian"

- name: Update flatpaks
  shell: flatpak update --noninteractive
  when:
    ansible_facts['os_family'] == "Debian"

- name: Update brew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Update mac apps from app store
  mas:
    upgrade_all: yes
  when:
    ansible_facts['os_family'] == "Darwin"

