---
- name: Update deb packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Update brew
  homebrew:
    update_homebrew: true
    upgrade_all: true
  when:
    ansible_facts['os_family'] == "Darwin"
