- name: Install virt-manager
  apt:
    name:
      - virt-manager
      - linux-headers-{{ ansible_kernel }}
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Install UTM on Macos
  homebrew_cask:
    name: utm
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Add user to libvirt group
  user:
    name: "{{ user_name }}"
    groups: libvirt
    append: yes
