---
- name: Install zsh
  ansible.builtin.apt:
    name:
      - zsh
      - curl
      - git
    state: present
    update_cache: true
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /bin/zsh
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Check if .zshrc file exists
  ansible.builtin.stat:
    path: ~/.zshrc
  register: zsh_file

- name: Make sure ~/.zshrc exists
  ansible.builtin.file:
    path: ~/.zshrc
    owner: "{{ user_name }}"
    group:
      "{{ 'staff' if ansible_facts['os_family'] == 'Darwin'
      else user_name }}"
    mode: 0750
    state: touch
  when: not zsh_file.stat.exists

- name: Check if .oh-my-zsh folder exists
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: register_name

- name: Install oh-my-zsh
  ansible.builtin.shell: >
    sh -c "$(curl -fsSL
    https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    --unattended
  when: not (register_name.stat.exists and register_name.stat.isdir)

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    version: master

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    version: master

- name: Mac Install diff-so-fancy
  homebrew:
    name:
      - diff-so-fancy
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Ubuntu install diff-so-fancy
  ansible.builtin.git:
    repo: https://github.com/so-fancy/diff-so-fancy.git
    dest: ~/.diff-so-fancy
    version: master
  when:
    ansible_facts['os_family'] == "Debian"

- name: Ubuntu add diff-so-fancy to $PATH
  ansible.builtin.file:
    src: "/home/{{ user_name }}/.diff-so-fancy/diff-so-fancy"
    dest: /usr/local/bin/diff-so-fancy
    mode: '0755'
    state: link
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: add plugins to .zshrc
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^plugins=\(git\)'
    line: >
      plugins=(
      git
      zsh-autosuggestions
      copypath
      copyfile
      copybuffer
      zsh-syntax-highlighting
      vi-mode
      )
    backrefs: true
