- name: Install zsh
  apt:
    name:
      - zsh
    state: present
    update_cache: yes
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Set zsh as default shell
  user:
    name: "{{ user_name }}"
    shell: /bin/zsh
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: yes

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      
- name: Mac Install diff-so-fancy
  homebrew:
    name:
      - diff-so-fancy
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Ubuntu install diff-so-fancy
  git:
    repo: https://github.com/so-fancy/diff-so-fancy.git
    dest: ~/.diff-so-fancy
  when:
    ansible_facts['os_family'] == "Debian"

- name: Ubuntu add diff-so-fancy to $PATH
  file:
    src: "/home/{{ user_name }}/.diff-so-fancy/diff-so-fancy"
    dest: /usr/local/bin/diff-so-fancy
    mode: '0755'
    state: link
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: add plugins to .zshrc
  lineinfile:
    path: ~/.zshrc
    regexp: '^plugins=\(git\)'
    line: plugins=(git zsh-autosuggestions copypath copyfile zsh-syntax-highlighting)
    backrefs: yes
