- name: Install zsh
  apt:
    name:
      - zsh
    state: present
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Set zsh as default shell
  user:
    name: "{{ user_name }}"
    shell: /bin/zsh
  become: true
  become_user: root
  when:
    ansible_facts['os_family'] == "Debian"

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install zsh-autosuggestions
  git:
    src: https://github.com/zsh-users/zsh-autosuggestions
    dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

- name: Install zsh-syntax-highlighting
  git:
    src: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
      
- name: Mac Install diff-so-fancy
  homebrew:
    name:
      - diff-so-fancy
  when:
    ansible_facts['os_family'] == "Darwin"

- name: Ubuntu install diff-so-fancy
  git:
    src: https://github.com/so-fancy/diff-so-fancy.git
    dest: ~/.diff-so-fancy
  when:
    ansible_facts['os_family'] == "Debian"

- name: add plugins to .zshrc
  lineinfile:
    path: ~/.zshrc
    search_string: 'plugins=(git)'
    line: plugins=(git zsh-autosuggestions copypath copyfile zsh-syntax-highlighting)
