---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Remove installed nodejs
  ansible.builtin.apt:
    name:
      - nodejs
    state: absent
  become: true
  become_user: root
  when: >
    not is_ubuntu18
    and ('nodejs' in ansible_facts.packages)
    and not ansible_facts.packages.nodejs[0].version is match('.*?18.*?')

- name: Remove installed nodejs
  ansible.builtin.apt:
    name:
      - nodejs
    state: absent
  become: true
  become_user: root
  when: >
    is_ubuntu18
    and ('nodejs' in ansible_facts.packages)
    and not ansible_facts.packages.nodejs[0].version is match('.*?16.*?')

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - gnupg
    state: present
  become: true
  become_user: root

- name: "Add nodejs apt key"
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: true
  become_user: root

- name: Add nodejs 16.x ppa for apt repo
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_16.x {{ ansible_facts.lsb.codename }} main"
    update_cache: true
  become: true
  become_user: root
  when: is_ubuntu18

- name: Add nodejs 18.x ppa for apt repo
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_facts.lsb.codename }} main"
    update_cache: true
  become: true
  become_user: root
  when: not is_ubuntu18

- name: Install node, npm
  ansible.builtin.apt:
    name:
      - nodejs
    state: present
  become: true
  become_user: root
