---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Remove installed nodejs
  ansible.builtin.apt:
    name:
      - nodejs
    state: absent
  become: true
  become_user: root
  when: >
    (is_ubuntu18 and not item.version is match('.*?16.*?')) or
    (not is_ubuntu18 and not item.version is match('.*?18.*?'))
  with_items: "{{ ansible_facts.packages.nodejs if 'nodejs' in ansible_facts.packages else [] }}"

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - gnupg
    state: present
  become: true
  become_user: root

- name: Add nodejs apt key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: true
  become_user: root

- name: Add nodejs ppa for apt repo
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ item.version }}.x {{ ansible_facts.lsb.codename }} main"
    update_cache: true
    state: present
    filename: nodesource
  become: true
  become_user: root
  when: item.os|bool
  with_items:
    - {os: '{{ is_ubuntu18 | bool }}', version: 16}
    - {os: '{{ (not is_ubuntu18) | bool }}', version: 18}

- name: Install node, npm
  ansible.builtin.apt:
    name:
      - nodejs
    state: present
  become: true
  become_user: root
