---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Remove installed nodejs
  ansible.builtin.apt:
    name:
      - nodejs
    state: absent
    autoremove: true
  become: true
  when: >
    (is_ubuntu18 and not item.version is match('.*?16.*?')) or
    (not is_ubuntu18 and not item.version is match('.*?18.*?'))
  with_items: "{{ ansible_facts.packages.nodejs if 'nodejs' in ansible_facts.packages else [] }}"

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gnupg
    state: present
  become: true

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Add nodejs apt key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: present
    keyring: /etc/apt/keyrings/nodesource.gpg
  become: true

- name: Add nodejs ppa for apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ item.version }}.x nodistro main"
    state: present
    filename: nodesource
    update_cache: true
  become: true
  when: item.os|bool
  with_items:
    - {os: '{{ is_ubuntu18 | bool }}', version: 16}
    - {os: '{{ (not is_ubuntu18) | bool }}', version: 18}

- name: Install node, npm
  ansible.builtin.apt:
    name:
      - nodejs
    state: present
  become: true
