---
- name: NodeJS (MacOS)
  ansible.builtin.import_tasks: mac.yml
  when: ansible_facts['os_family'] == "Darwin"

- name: NodeJS (Debian)
  ansible.builtin.import_tasks: deb.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install yarn
  community.general.npm:
    name: yarn
    global: true
    state: present
  become: true
  changed_when: false
