---
- name: Install zsh
  ansible.builtin.apt:
    name:
      - zsh
      - curl
      - git
    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Clone zsh config
  ansible.builtin.git:
    repo: https://github.com/altayatalayy/zsh-config.git
    dest: ~/.config/zsh
    version: main

- name: Create symbolic link for .zshenv
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.config/zsh/.zshenv"
    dest: "{{ ansible_env.HOME }}/.zshenv"
    state: link

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_env.HOME }}/.config/zsh/plugins/zsh-autosuggestions"
    version: master

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.config/zsh/plugins/zsh-syntax-highlighting"
    version: master

- name: Install fzf
  ansible.builtin.unarchive:
    src: https://github.com/junegunn/fzf/releases/download/0.48.0/fzf-0.48.0-linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
    become: true
