---
dependency:
  name: galaxy
  options:
    collection-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: altayatalay/docker-ubuntu2204-ansible:latest
    privileged: true
    pre_build_image: true
    user: testuser

provisioner:
  name: ansible

verifier:
  name: ansible
