---
dependency:
  name: galaxy
  options:
    collection-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: altayatalay/docker-ubuntu2204-ansible:latest

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          user_name: testuser

verifier:
  name: ansible
