---
- name: Set git default branch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Set default editor for git
  community.general.git_config:
    name: core.editor
    scope: global
    value: nvim

- name: Configure Git to use SSH for GitHub URLs
  community.general.git_config:
    name: url."ssh://git@github.com/".insteadOf
    value: "https://github.com/"
    scope: global
