---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Remove old tmux
  ansible.builtin.apt:
    name:
      - tmux
    state: absent
    autoremove: true
  become: true
  when: >
    ('tmux' in ansible_facts.packages)
    and not ansible_facts.packages.tmux[0].version == tmux_version

- name: Install tmux (Ubuntu)
  ansible.builtin.apt:
    deb:
      "https://github.com/altayatalayy/neovim-package/releases/download/v0.1.1/tmux.deb"
  become: true
  when: not is_debian10

- name: Install tmux (Debian)
  ansible.builtin.apt:
    deb:
      "https://github.com/altayatalayy/neovim-package/releases/download/v0.1.1/tmux10.deb"
  become: true
  when: is_debian10
