---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Remove installed tmux
  ansible.builtin.apt:
    name:
      - tmux
    state: absent
    autoremove: true
  become: true
  become_user: root
  when: >
    ('tmux' in ansible_facts.packages)
    and not ansible_facts.packages.tmux[0].version == tmux_version

- name: Check for existing tmux install
  ansible.builtin.stat:
    path: "{{ tmux_bin_path }}"
  register: result_tmux_installed

- name: Check tmux version
  ansible.builtin.command: "{{ tmux_bin_path }} -V"
  register: result_tmux_version
  when: result_tmux_installed is defined and result_tmux_installed.stat.exists
  changed_when: false

- name: Set build_tmux
  ansible.builtin.set_fact:
    build_tmux: >
      {{ result_tmux_version is skipped or
      not result_tmux_version.stdout_lines[0] is match('.*3.3a') }}

- name: Remove old tmux
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /usr/local/bin/tmux
    - /usr/local/share/man/man.1/tmux.1
  become: true
  become_user: root
  when: build_tmux|lower|trim|bool

- name: Make sure tmux-source folder exists
  ansible.builtin.file:
    path: ~/tmux-source
    state: directory
    mode: '0766'
  when: build_tmux|lower|trim|bool

- name: Download tmux source code
  ansible.builtin.unarchive:
    src: https://github.com/tmux/tmux/releases/download/3.3a/tmux-3.3a.tar.gz
    dest: ~/tmux-source
    mode: '0760'
    remote_src: true
    extra_opts: [--strip-components=1]
  when: build_tmux|lower|trim|bool

- name: Install build dependencies
  ansible.builtin.apt:
    name:
      - libevent-dev
      - ncurses-dev
      - build-essential
      - bison
      - pkg-config
  become: true
  become_user: root
  when: build_tmux|lower|trim|bool

- name: Run configure
  ansible.builtin.shell: cd ~/tmux-source && ./configure
  when: build_tmux|lower|trim|bool

- name: Compile tmux
  community.general.make:
    chdir: ~/tmux-source
  when: build_tmux|lower|trim|bool

- name: Run install
  community.general.make:
    chdir: '/home/{{ user_name }}/tmux-source'
    target: install
  become: true
  become_user: root
  when: build_tmux|lower|trim|bool

- name: Delete tmux-source folder
  ansible.builtin.file:
    path: ~/tmux-source
    state: absent
  when: build_tmux|lower|trim|bool
