---
- name: Tmux (MacOS)
  ansible.builtin.import_tasks: mac.yml
  when: ansible_facts['os_family'] == "Darwin"

- name: Nvim (Debian)
  ansible.builtin.import_tasks: deb.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Clone tmux config
  ansible.builtin.git:
    repo: https://github.com/altayatalayy/tmux-config.git
    dest: "{{ ansible_env.HOME }}/.config/tmux"
    version: main

- name: Install tmux tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm"
    version: master
