---
dependency:
  name: galaxy
  options:
    collection-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance-1
    image: altayatalay/docker-ubuntu1804-ansible
    privileged: true
    pre_build_image: true
    user: testuser
  - name: instance-2
    image: altayatalay/docker-ubuntu2004-ansible
    privileged: true
    pre_build_image: true
    user: testuser
  - name: instance-3
    image: altayatalay/docker-ubuntu2204-ansible
    privileged: true
    pre_build_image: true
    user: testuser
  - name: instance-4
    image: altayatalay/docker-debian10-ansible
    privileged: true
    pre_build_image: true
    user: testuser

provisioner:
  name: ansible

verifier:
  name: ansible
