---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Remove installed neovim
  ansible.builtin.apt:
    name:
      - neovim
    state: absent
    autoremove: true
  become: true
  when: >
    ('neovim' in ansible_facts.packages)
    and not ansible_facts.packages.neovim[0].version == nvim_version

- name: Install required packages with apt
  ansible.builtin.apt:
    name:
      - curl
      - git
      - python3-pip
      - python3-venv
  become: true

- name: Install required packages for nvim plugins
  ansible.builtin.apt:
    name:
      - cmake
      - make
      - gcc
      - unzip
  become: true

- name: Install ripgrep, Ubuntu 18.10+
  ansible.builtin.apt:
    name:
      - ripgrep
      - fd-find
  become: true
  when: >
    not (is_ubuntu18 or is_debian10)

- name: Install ripgrep, Ubuntu 18.04
  ansible.builtin.apt:
    deb: "https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb"
  become: true
  when: (is_ubuntu18 or is_debian10)

- name: Install cppcheck
  ansible.builtin.apt:
    name:
      - cppcheck
  become: true

- name: Install neovim Ubuntu 22.04
  ansible.builtin.apt:
    deb: "https://github.com/altayatalayy/neovim-package/releases/download/v0.1.7/nvim-linux64-23.deb"
  become: true
  when: >
    ansible_facts.distribution == 'Ubuntu' and
    ansible_facts.distribution_major_version == '23'

- name: Install neovim Ubuntu 22.04
  ansible.builtin.apt:
    deb: "https://github.com/altayatalayy/neovim-package/releases/download/v0.1.7/nvim-linux64-22.deb"
  become: true
  when: >
    ansible_facts.distribution == 'Ubuntu' and
    ansible_facts.distribution_major_version == '22'

- name: Install neovim Ubuntu 20.04
  ansible.builtin.apt:
    deb: "https://github.com/altayatalayy/neovim-package/releases/download/v0.1.7/nvim-linux64-20.deb"
  become: true
  when: >
    ansible_facts.distribution == 'Ubuntu' and
    ansible_facts.distribution_major_version == '20'

- name: Install neovim Ubuntu 18.04
  ansible.builtin.apt:
    deb: "https://github.com/altayatalayy/neovim-package/releases/download/v0.1.7/nvim-linux64-18.deb"
  become: true
  when: >
    (is_ubuntu18 or is_debian10)
